spring:
  application:
    name: KeycloakService

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

server:
  port: 8000

keycloak:
  url: http://localhost:8081/auth
  realm: bitlab-realm
  client: bitlab-user-service-client
  client-secret: 0CAB6IkzWoK8LvhlE9f1xaILvaytIcEm
  username: bitlab_admin
  password: qweqwe
  grant-type: password
